# Generated by Django 4.2.1 on 2023-05-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_friends_second_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequests',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
