# Generated by Django 4.2.1 on 2023-05-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_friends_first_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='first_user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='friends',
            name='second_user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='friendshiprequests',
            name='from_user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='friendshiprequests',
            name='to_user',
            field=models.CharField(max_length=50),
        ),
    ]
