# Generated by Django 4.2.1 on 2023-05-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_friends_first_user_alter_friends_second_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='first_user',
            new_name='core_person',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='second_user',
            new_name='friend',
        ),
    ]
